# Generated by Django 5.2.17 on 2026-08-28 02:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Destino",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=120, verbose_name="Nome")),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="Preenchido automaticamente a partir do nome.",
                        max_length=140,
                        unique=True,
                        verbose_name="Slug",
                    ),
                ),
                ("pais", models.CharField(max_length=80, verbose_name="País")),
                (
                    "continente",
                    models.CharField(
                        choices=[
                            ("AF", "África"),
                            ("AM", "Américas"),
                            ("AS", "Ásia"),
                            ("EU", "Europa"),
                            ("OC", "Oceania"),
                        ],
                        default="AM",
                        max_length=2,
                        verbose_name="Continente",
                    ),
                ),
                ("descricao", models.TextField(verbose_name="Descrição")),
                (
                    "imagem_capa",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="destinos/",
                        verbose_name="Imagem de capa",
                    ),
                ),
                (
                    "preco_medio_diaria",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        verbose_name="Preço médio da diária (R$)",
                    ),
                ),
                (
                    "melhor_epoca",
                    models.CharField(
                        blank=True,
                        max_length=120,
                        verbose_name="Melhor época para visitar",
                    ),
                ),
                (
                    "destaque",
                    models.BooleanField(
                        default=False, verbose_name="Destaque na página inicial"
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
            ],
            options={
                "verbose_name": "Destino",
                "verbose_name_plural": "Destinos",
                "ordering": ["-destaque", "nome"],
            },
        ),
        migrations.CreateModel(
            name="Hospedagem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=120, verbose_name="Nome")),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("hotel", "Hotel"),
                            ("pousada", "Pousada"),
                            ("hostel", "Hostel"),
                            ("resort", "Resort"),
                            ("apartamento", "Apartamento"),
                            ("casa", "Casa de temporada"),
                        ],
                        default="hotel",
                        max_length=20,
                        verbose_name="Tipo",
                    ),
                ),
                ("descricao", models.TextField(blank=True, verbose_name="Descrição")),
                (
                    "preco_diaria",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=8,
                        verbose_name="Preço da diária (R$)",
                    ),
                ),
                (
                    "imagem",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="hospedagens/",
                        verbose_name="Imagem principal",
                    ),
                ),
                (
                    "endereco",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Endereço"
                    ),
                ),
                ("site", models.URLField(blank=True, verbose_name="Site")),
                (
                    "disponivel",
                    models.BooleanField(default=True, verbose_name="Disponível"),
                ),
                (
                    "destino",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hospedagens",
                        to="destinations.destino",
                        verbose_name="Destino",
                    ),
                ),
            ],
            options={
                "verbose_name": "Hospedagem",
                "verbose_name_plural": "Hospedagens",
                "ordering": ["preco_diaria"],
            },
        ),
        migrations.CreateModel(
            name="ImagemDestino",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "imagem",
                    models.ImageField(
                        upload_to="destinos/galeria/", verbose_name="Imagem"
                    ),
                ),
                (
                    "legenda",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Legenda"
                    ),
                ),
                (
                    "destino",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="imagens",
                        to="destinations.destino",
                        verbose_name="Destino",
                    ),
                ),
            ],
            options={
                "verbose_name": "Imagem do destino",
                "verbose_name_plural": "Imagens do destino",
            },
        ),
        migrations.CreateModel(
            name="ImagemHospedagem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "imagem",
                    models.ImageField(
                        upload_to="hospedagens/galeria/", verbose_name="Imagem"
                    ),
                ),
                (
                    "legenda",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Legenda"
                    ),
                ),
                (
                    "hospedagem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="imagens",
                        to="destinations.hospedagem",
                        verbose_name="Hospedagem",
                    ),
                ),
            ],
            options={
                "verbose_name": "Imagem da hospedagem",
                "verbose_name_plural": "Imagens da hospedagem",
            },
        ),
    ]
