# Generated by Django 5.2.17 on 2026-09-02 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destino',
            name='dias',
            field=models.CharField(blank=True, help_text='Ex.: 6 dias.', max_length=20, verbose_name='Duração em dias'),
        ),
        migrations.AddField(
            model_name='destino',
            name='estado',
            field=models.CharField(blank=True, help_text='Ex.: Tocantins. Sem isso, mostra o país.', max_length=60, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='destino',
            name='hospedagem_sub',
            field=models.CharField(blank=True, help_text='Ex.: A duas quadras da Ilha do Amor.', max_length=120, verbose_name='Chamada da hospedagem'),
        ),
        migrations.AddField(
            model_name='destino',
            name='incluso',
            field=models.TextField(blank=True, help_text='Um item por linha.', verbose_name='O que está incluso'),
        ),
        migrations.AddField(
            model_name='destino',
            name='informacoes',
            field=models.TextField(blank=True, help_text='Um item por linha.', verbose_name='Informações importantes'),
        ),
        migrations.AddField(
            model_name='destino',
            name='mes_ano',
            field=models.CharField(blank=True, help_text='Ex.: Junho 2027.', max_length=40, verbose_name='Mês e ano'),
        ),
        migrations.AddField(
            model_name='destino',
            name='noites',
            field=models.CharField(blank=True, help_text='Ex.: 5 noites.', max_length=20, verbose_name='Duração em noites'),
        ),
        migrations.AddField(
            model_name='destino',
            name='periodo',
            field=models.CharField(blank=True, help_text='Só os dias. Ex.: 16 a 21.', max_length=40, verbose_name='Período'),
        ),
        migrations.AddField(
            model_name='destino',
            name='preco_base',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valor do quarto duplo, que abre o card de reserva. Sem isso, calcula a partir da diária média.', max_digits=9, null=True, verbose_name='Preço da viagem por pessoa (R$)'),
        ),
        migrations.AddField(
            model_name='destino',
            name='proxima_saida',
            field=models.CharField(blank=True, help_text='Ex.: 16 a 21 de Junho de 2027.', max_length=120, verbose_name='Próxima saída'),
        ),
        migrations.AddField(
            model_name='destino',
            name='regiao',
            field=models.CharField(blank=True, help_text='Ex.: Norte. Sem isso, mostra o continente.', max_length=60, verbose_name='Região'),
        ),
        migrations.AddField(
            model_name='destino',
            name='selo',
            field=models.CharField(blank=True, help_text='Aparece sobre o título. Ex.: Expedição.', max_length=40, verbose_name='Selo'),
        ),
        migrations.AddField(
            model_name='destino',
            name='subtitulo',
            field=models.CharField(blank=True, help_text='A frase logo abaixo do nome, na capa.', max_length=160, verbose_name='Subtítulo'),
        ),
        migrations.AddField(
            model_name='destino',
            name='vagas',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Vagas disponíveis'),
        ),
        migrations.CreateModel(
            name='DestaqueViagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveSmallIntegerField(default=0, verbose_name='Ordem')),
                ('texto', models.CharField(help_text='Ex.: Fervedouro do Alecrim.', max_length=120, verbose_name='Destaque')),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destaques_viagem', to='destinations.destino', verbose_name='Destino')),
            ],
            options={
                'verbose_name': 'Destaque da viagem',
                'verbose_name_plural': 'Destaques da viagem',
                'ordering': ['ordem', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DiaRoteiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveSmallIntegerField(default=0, verbose_name='Ordem')),
                ('titulo', models.CharField(help_text='Ex.: Dia 1 — Chegada em Santarém.', max_length=120, verbose_name='Título')),
                ('resumo', models.CharField(help_text='A linha que aparece com o dia fechado.', max_length=200, verbose_name='Resumo')),
                ('detalhe', models.TextField(blank=True, help_text='O texto que abre quando a pessoa clica no dia.', verbose_name='Detalhe')),
                ('imagem', models.ImageField(blank=True, help_text='Opcional: sem foto, usa uma da galeria do destino.', null=True, upload_to='roteiro/', verbose_name='Foto do dia')),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roteiro', to='destinations.destino', verbose_name='Destino')),
            ],
            options={
                'verbose_name': 'Dia do roteiro',
                'verbose_name_plural': 'Roteiro dia a dia',
                'ordering': ['ordem', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PerguntaFrequente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveSmallIntegerField(default=0, verbose_name='Ordem')),
                ('pergunta', models.CharField(max_length=200, verbose_name='Pergunta')),
                ('resposta', models.TextField(verbose_name='Resposta')),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perguntas', to='destinations.destino', verbose_name='Destino')),
            ],
            options={
                'verbose_name': 'Pergunta frequente',
                'verbose_name_plural': 'Perguntas frequentes',
                'ordering': ['ordem', 'id'],
            },
        ),
    ]
