# Generated by Django 5.2.17 on 2026-09-03 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0002_destino_dias_destino_estado_destino_hospedagem_sub_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='destino',
            index=models.Index(fields=['nome'], name='destino_nome_idx'),
        ),
        migrations.AddIndex(
            model_name='destino',
            index=models.Index(fields=['pais'], name='destino_pais_idx'),
        ),
        migrations.AddIndex(
            model_name='destino',
            index=models.Index(fields=['continente'], name='destino_continente_idx'),
        ),
    ]
