# Generated by Django 5.2.17 on 2026-09-04 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0003_destino_destino_nome_idx_destino_destino_pais_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='destino',
            name='soar_60',
            field=models.BooleanField(default=False, help_text='Marque as viagens de ritmo mais tranquilo, que aparecem na página do Soar 60+. Se nenhuma estiver marcada, a página mostra o catálogo inteiro.', verbose_name='Faz parte do Soar 60+'),
        ),
    ]
