# Generated by Django 5.2.17 on 2026-09-18 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0004_destino_soar_60'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='destino',
            name='destino_continente_idx',
        ),
        migrations.RemoveField(
            model_name='destino',
            name='continente',
        ),
        migrations.AddField(
            model_name='destino',
            name='data_ida',
            field=models.DateField(blank=True, help_text='Escolha no calendário o dia de saída.', null=True, verbose_name='Data de ida'),
        ),
        migrations.AddField(
            model_name='destino',
            name='data_volta',
            field=models.DateField(blank=True, help_text='O dia do retorno. Período, mês, duração e próxima saída são preenchidos a partir das datas.', null=True, verbose_name='Data de volta'),
        ),
        migrations.AlterField(
            model_name='destino',
            name='pais',
            field=models.CharField(default='Brasil', max_length=80, verbose_name='País'),
        ),
        migrations.AlterField(
            model_name='destino',
            name='periodo',
            field=models.CharField(blank=True, help_text='Preenchido a partir das datas de ida e volta.', max_length=40, verbose_name='Período'),
        ),
        migrations.AlterField(
            model_name='destino',
            name='regiao',
            field=models.CharField(blank=True, choices=[('Norte', 'Norte'), ('Nordeste', 'Nordeste'), ('Centro-Oeste', 'Centro-Oeste'), ('Sudeste', 'Sudeste'), ('Sul', 'Sul')], help_text='Região do Brasil onde fica o destino.', max_length=20, verbose_name='Região'),
        ),
    ]
