# Generated by Django 5.2.17 on 2026-09-18 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0005_remove_destino_destino_continente_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destino',
            name='preco_base',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valor do quarto duplo, que abre o card de reserva. Sem isso, calcula a partir da diária média.', max_digits=9, null=True, verbose_name='Preço da viagem por tipo de quarto (R$)'),
        ),
    ]
