# Generated by Django 5.2.17 on 2026-09-18 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0006_alter_destino_preco_base'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hospedagem',
            options={'ordering': ['nome'], 'verbose_name': 'Hospedagem', 'verbose_name_plural': 'Hospedagens'},
        ),
        migrations.RemoveField(
            model_name='hospedagem',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='hospedagem',
            name='disponivel',
        ),
        migrations.RemoveField(
            model_name='hospedagem',
            name='preco_diaria',
        ),
        migrations.RemoveField(
            model_name='hospedagem',
            name='site',
        ),
        migrations.RemoveField(
            model_name='hospedagem',
            name='tipo',
        ),
        migrations.AddField(
            model_name='hospedagem',
            name='pacote_completo',
            field=models.BooleanField(default=True, help_text='A hospedagem já está inclusa no pacote da viagem.', verbose_name='Incluso no pacote completo'),
        ),
        migrations.AlterField(
            model_name='hospedagem',
            name='endereco',
            field=models.CharField(blank=True, help_text='Onde a hospedagem fica.', max_length=200, verbose_name='Endereço'),
        ),
    ]
