# Generated by Django 5.2.17 on 2026-09-23 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0007_alter_hospedagem_options_remove_hospedagem_descricao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diaroteiro',
            name='titulo',
            field=models.CharField(help_text='Ex.: Dia 1: Chegada em Santarém.', max_length=120, verbose_name='Título'),
        ),
    ]
