# Generated by Django 5.2.17 on 2026-09-23 04:17

import django.db.models.deletion
from django.db import migrations, models


def copiar_datas_antigas(apps, schema_editor):
    """Quem já tinha ida e volta no destino ganha essa data como primeira saída."""
    Destino = apps.get_model('destinations', 'Destino')
    Saida = apps.get_model('destinations', 'Saida')
    for destino in Destino.objects.exclude(data_ida=None).exclude(data_volta=None):
        Saida.objects.get_or_create(destino=destino, data_ida=destino.data_ida,
                                    data_volta=destino.data_volta,
                                    defaults={'vagas': destino.vagas})


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0009_tira_travessao_do_conteudo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Saida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_ida', models.DateField(help_text='Dia em que o grupo sai.', verbose_name='Ida')),
                ('data_volta', models.DateField(help_text='Dia do retorno.', verbose_name='Volta')),
                ('vagas', models.PositiveSmallIntegerField(blank=True, help_text='Em branco, o site mostra "consulte". Com 0, aparece como esgotada.', null=True, verbose_name='Vagas')),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saidas', to='destinations.destino', verbose_name='Destino')),
            ],
            options={
                'verbose_name': 'Saída',
                'verbose_name_plural': 'Saídas',
                'ordering': ['data_ida', 'id'],
            },
        ),
        migrations.RunPython(copiar_datas_antigas, migrations.RunPython.noop),
    ]
