# Generated by Django 5.2.17 on 2026-09-25 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0010_saidas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destino',
            name='preco_base',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valor por pessoa em quarto de casal, que abre o card de reserva. Sem isso, calcula a partir da diária média.', max_digits=9, null=True, verbose_name='Preço da viagem por pessoa (R$)'),
        ),
    ]
