# Generated by Django 5.2.17 on 2026-09-25 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0011_preco_por_pessoa'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlideInicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(help_text='Foto deitada e grande (pelo menos 1600 px de largura). Ela ocupa a tela inteira, então o assunto principal deve ficar mais para a direita: o título aparece à esquerda.', upload_to='inicio/', verbose_name='Foto')),
                ('legenda', models.CharField(blank=True, help_text='Ex.: Cachoeira no Jalapão. Lida por quem usa leitor de tela.', max_length=120, verbose_name='Descrição da foto')),
                ('ordem', models.PositiveSmallIntegerField(default=0, verbose_name='Ordem')),
                ('ativo', models.BooleanField(default=True, verbose_name='Aparece no site')),
            ],
            options={
                'verbose_name': 'Foto do topo da página inicial',
                'verbose_name_plural': 'Fotos do topo da página inicial',
                'ordering': ['ordem', 'id'],
            },
        ),
    ]
