# Generated by Django 5.2.17 on 2026-09-25 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0012_slides_inicio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destino',
            name='preco_medio_diaria',
        ),
        migrations.AlterField(
            model_name='destino',
            name='preco_base',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valor por pessoa em quarto de casal, que abre o card de reserva. Sem ele, a página mostra "sob consulta".', max_digits=9, null=True, verbose_name='Preço da viagem por pessoa (R$)'),
        ),
    ]
