# Generated by Django 5.2.17 on 2026-09-30 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0013_sem_preco_diaria'),
    ]

    operations = [
        migrations.AddField(
            model_name='destino',
            name='nao_incluso',
            field=models.TextField(blank=True, help_text='Um item por linha. Ex.: Passagem aérea até o ponto de encontro. Em branco, a página só mostra o que está incluso.', verbose_name='O que não está incluso'),
        ),
    ]
