# Generated by Django 5.2.17 on 2026-09-30 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0014_nao_incluso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diaroteiro',
            name='detalhe',
            field=models.TextField(blank=True, help_text='O texto que abre quando a pessoa clica no dia. Cada linha vira um tópico no site.', verbose_name='Detalhe'),
        ),
    ]
