# Generated by Django 5.2.17 on 2026-09-30 03:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0015_roteiro_em_topicos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interessado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, verbose_name='Nome')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('whatsapp', models.CharField(max_length=20, verbose_name='WhatsApp')),
                ('cep', models.CharField(max_length=9, verbose_name='CEP')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Pedido em')),
                ('destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interessados', to='destinations.destino', verbose_name='Viagem')),
            ],
            options={
                'verbose_name': 'Interessado',
                'verbose_name_plural': 'Interessados ("Saiba mais" da viagem)',
                'ordering': ['-criado_em'],
            },
        ),
    ]
