# Generated by Django 5.2.17 on 2026-09-30 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0004_dois_fatores'),
        ('destinations', '0016_interessados'),
    ]

    operations = [
        migrations.AddField(
            model_name='interessado',
            name='agencias',
            field=models.ManyToManyField(blank=True, help_text='Marque as agências que vão atender esta pessoa. Ela aparece no painel de cada agência marcada.', related_name='interessados', to='contas.perfilagente', verbose_name='Enviar para as agências'),
        ),
    ]
