# Generated by Django 5.2.17 on 2026-10-03 03:04

import django.db.models.deletion
import soar.videos
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0017_interessado_enviado_para_agencias'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoSoar60',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Ex.: Como é uma viagem 60+ com a Soar.', max_length=120, verbose_name='Título')),
                ('arquivo', models.FileField(help_text='MP4 ou WebM, até 100 MB. Vídeos curtos (até 1 minuto) carregam mais rápido, principalmente no celular.', upload_to='soar60/videos/', validators=[soar.videos.validar_video], verbose_name='Vídeo')),
                ('capa', models.ImageField(blank=True, help_text='Opcional. Aparece antes de o vídeo tocar.', null=True, upload_to='soar60/capas/', verbose_name='Foto de capa')),
                ('ordem', models.PositiveSmallIntegerField(default=0, verbose_name='Ordem')),
                ('ativo', models.BooleanField(default=True, verbose_name='Aparece no site')),
            ],
            options={
                'verbose_name': 'Vídeo do Soar 60+',
                'verbose_name_plural': 'Vídeos do Soar 60+',
                'ordering': ['ordem', 'id'],
            },
        ),
        migrations.AlterModelOptions(
            name='slideinicio',
            options={'ordering': ['ordem', 'id'], 'verbose_name': 'Foto ou vídeo do topo da página inicial', 'verbose_name_plural': 'Fotos e vídeos do topo da página inicial'},
        ),
        migrations.AddField(
            model_name='slideinicio',
            name='video',
            field=models.FileField(blank=True, help_text='Toca sem som e em repetição no lugar da foto, que vira a capa. MP4 ou WebM, até 100 MB. Vídeos curtos (até 1 minuto) carregam mais rápido, principalmente no celular.', upload_to='inicio/videos/', validators=[soar.videos.validar_video], verbose_name='Vídeo (opcional)'),
        ),
        migrations.CreateModel(
            name='VideoDestino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(help_text='MP4 ou WebM, até 100 MB. Vídeos curtos (até 1 minuto) carregam mais rápido, principalmente no celular.', upload_to='destinos/videos/', validators=[soar.videos.validar_video], verbose_name='Vídeo')),
                ('capa', models.ImageField(blank=True, help_text='Opcional. Aparece antes de o vídeo tocar.', null=True, upload_to='destinos/videos/capas/', verbose_name='Foto de capa')),
                ('legenda', models.CharField(blank=True, max_length=200, verbose_name='Legenda')),
                ('ordem', models.PositiveSmallIntegerField(default=0, verbose_name='Ordem')),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='destinations.destino', verbose_name='Destino')),
            ],
            options={
                'verbose_name': 'Vídeo do destino',
                'verbose_name_plural': 'Vídeos do destino',
                'ordering': ['ordem', 'id'],
            },
        ),
    ]
