# Generated by Django 5.2.17 on 2026-10-03 03:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0018_videos'),
    ]

    operations = [
        migrations.AddField(
            model_name='saida',
            name='quartos_casal',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Quartos Casal'),
        ),
        migrations.AddField(
            model_name='saida',
            name='quartos_duplo',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Quartos Duplo'),
        ),
        migrations.AddField(
            model_name='saida',
            name='quartos_single',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Quartos Single'),
        ),
        migrations.AddField(
            model_name='saida',
            name='quartos_triplo',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Quartos Triplo'),
        ),
        migrations.AlterField(
            model_name='destino',
            name='preco_base',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='O menor preço por pessoa entre os quartos. Sem preço, a página mostra "sob consulta".', max_digits=9, null=True, verbose_name='A partir de (R$ por pessoa)'),
        ),
        migrations.AlterField(
            model_name='saida',
            name='vagas',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Em branco, o site mostra "consulte". Com 0, aparece como esgotada.', null=True, verbose_name='Vagas (pessoas)'),
        ),
        migrations.CreateModel(
            name='ServicoViagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icone', models.CharField(choices=[('ic-onibus', 'Ônibus'), ('ic-aviao', 'Avião'), ('ic-barco', 'Barco'), ('ic-cama', 'Cama'), ('ic-hotel', 'Hotel'), ('ic-guia', 'Guia'), ('ic-grupo', 'Grupo'), ('ic-escudo', 'Seguro'), ('ic-camera', 'Câmera'), ('ic-coracao', 'Coração'), ('ic-talheres', 'Refeições'), ('ic-cafe', 'Café'), ('ic-ticket', 'Ingresso'), ('ic-mapa', 'Mapa'), ('ic-pin', 'Local'), ('ic-mala', 'Mala'), ('ic-mochila', 'Mochila'), ('ic-sol', 'Sol'), ('ic-lua', 'Noite'), ('ic-piscina', 'Piscina'), ('ic-wifi', 'Wi-Fi'), ('ic-ar', 'Ar-condicionado'), ('ic-relogio', 'Horário'), ('ic-calendario', 'Calendário'), ('ic-fone', 'Atendimento'), ('ic-estrela-c', 'Estrela'), ('ic-check', 'Confirmado')], default='ic-onibus', max_length=30, verbose_name='Ícone')),
                ('titulo', models.CharField(help_text='Ex.: Transporte', max_length=40, verbose_name='Primeira linha')),
                ('sub', models.CharField(blank=True, help_text='Ex.: confortável', max_length=40, verbose_name='Segunda linha')),
                ('ordem', models.PositiveSmallIntegerField(default=0, verbose_name='Ordem')),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicos', to='destinations.destino', verbose_name='Destino')),
            ],
            options={
                'verbose_name': 'Serviço da viagem',
                'verbose_name_plural': 'Serviços da viagem',
                'ordering': ['ordem', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PrecoQuarto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('single', 'Single'), ('casal', 'Casal'), ('duplo', 'Duplo (Twin)'), ('triplo', 'Triplo')], max_length=12, verbose_name='Quarto')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Preço por pessoa (R$)')),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precos', to='destinations.destino', verbose_name='Destino')),
            ],
            options={
                'verbose_name': 'Preço por quarto',
                'verbose_name_plural': 'Preços por quarto',
                'constraints': [models.UniqueConstraint(fields=('destino', 'tipo'), name='um_preco_por_tipo_de_quarto')],
            },
        ),
    ]
