# Generated by Django 5.2.17 on 2026-10-03 04:39

import django.db.models.deletion
import soar.videos
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0020_precos_existentes_por_quarto'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaginaSobre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Sobre a Soar', max_length=80, verbose_name='Título da capa')),
                ('subtitulo', models.CharField(blank=True, default='Viagens em grupo pelo Brasil, para quem quer ir além do óbvio.', max_length=200, verbose_name='Frase da capa')),
                ('capa', models.ImageField(blank=True, help_text='Foto deitada e grande (1920 x 1080 px). Sem foto, usa uma ilustração da Soar.', null=True, upload_to='sobre/', verbose_name='Foto da capa')),
                ('video_capa', models.FileField(blank=True, help_text='Toca sem som e em repetição atrás do título; a foto vira a capa. MP4 ou WebM, até 100 MB. Vídeos curtos (até 1 minuto) carregam mais rápido, principalmente no celular.', upload_to='sobre/videos/', validators=[soar.videos.validar_video], verbose_name='Vídeo da capa (opcional)')),
                ('historia_titulo', models.CharField(default='Quem somos', max_length=80, verbose_name='Título do texto principal')),
                ('historia', models.TextField(blank=True, help_text='A história da Soar. Para começar um parágrafo novo, deixe uma linha em branco.', verbose_name='Texto principal')),
                ('historia_foto', models.ImageField(blank=True, null=True, upload_to='sobre/', verbose_name='Foto ao lado do texto')),
                ('diferenciais_titulo', models.CharField(default='Por que viajar com a Soar', max_length=80, verbose_name='Título dos diferenciais')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Página Sobre a Soar',
                'verbose_name_plural': 'Página Sobre a Soar',
            },
        ),
        migrations.CreateModel(
            name='NumeroSobre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(help_text='Ex.: +2.000', max_length=20, verbose_name='Número')),
                ('legenda', models.CharField(help_text='Ex.: viajantes levados', max_length=60, verbose_name='Legenda')),
                ('ordem', models.PositiveSmallIntegerField(default=0, verbose_name='Ordem')),
                ('pagina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='numeros', to='destinations.paginasobre')),
            ],
            options={
                'verbose_name': 'número',
                'verbose_name_plural': 'Números da Soar (opcional; sem nenhum, a faixa não aparece)',
                'ordering': ['ordem', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FotoSobre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='sobre/galeria/', verbose_name='Foto')),
                ('legenda', models.CharField(blank=True, max_length=120, verbose_name='Legenda')),
                ('ordem', models.PositiveSmallIntegerField(default=0, verbose_name='Ordem')),
                ('pagina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='destinations.paginasobre')),
            ],
            options={
                'verbose_name': 'foto',
                'verbose_name_plural': 'Fotos (opcional; sem nenhuma, a galeria não aparece)',
                'ordering': ['ordem', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DiferencialSobre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icone', models.CharField(choices=[('ic-onibus', 'Ônibus'), ('ic-aviao', 'Avião'), ('ic-barco', 'Barco'), ('ic-cama', 'Cama'), ('ic-hotel', 'Hotel'), ('ic-guia', 'Guia'), ('ic-grupo', 'Grupo'), ('ic-escudo', 'Seguro'), ('ic-camera', 'Câmera'), ('ic-coracao', 'Coração'), ('ic-talheres', 'Refeições'), ('ic-cafe', 'Café'), ('ic-ticket', 'Ingresso'), ('ic-mapa', 'Mapa'), ('ic-pin', 'Local'), ('ic-mala', 'Mala'), ('ic-mochila', 'Mochila'), ('ic-sol', 'Sol'), ('ic-lua', 'Noite'), ('ic-piscina', 'Piscina'), ('ic-wifi', 'Wi-Fi'), ('ic-ar', 'Ar-condicionado'), ('ic-relogio', 'Horário'), ('ic-calendario', 'Calendário'), ('ic-fone', 'Atendimento'), ('ic-estrela-c', 'Estrela'), ('ic-check', 'Confirmado')], default='ic-check', max_length=30, verbose_name='Ícone')),
                ('titulo', models.CharField(max_length=60, verbose_name='Título')),
                ('texto', models.TextField(blank=True, max_length=300, verbose_name='Texto')),
                ('ordem', models.PositiveSmallIntegerField(default=0, verbose_name='Ordem')),
                ('pagina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diferenciais', to='destinations.paginasobre')),
            ],
            options={
                'verbose_name': 'diferencial',
                'verbose_name_plural': 'Diferenciais',
                'ordering': ['ordem', 'id'],
            },
        ),
    ]
