# Generated by Django 5.2.17 on 2026-10-03 05:13

import soar.videos
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0022_texto_inicial_sobre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destino',
            name='imagem_capa',
            field=models.ImageField(blank=True, null=True, upload_to='destinos/', validators=[soar.videos.validar_foto], verbose_name='Imagem de capa'),
        ),
        migrations.AlterField(
            model_name='diaroteiro',
            name='imagem',
            field=models.ImageField(blank=True, help_text='Opcional: sem foto, usa uma da galeria do destino.', null=True, upload_to='roteiro/', validators=[soar.videos.validar_foto], verbose_name='Foto do dia'),
        ),
        migrations.AlterField(
            model_name='fotosobre',
            name='imagem',
            field=models.ImageField(upload_to='sobre/galeria/', validators=[soar.videos.validar_foto], verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='hospedagem',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='hospedagens/', validators=[soar.videos.validar_foto], verbose_name='Imagem principal'),
        ),
        migrations.AlterField(
            model_name='imagemdestino',
            name='imagem',
            field=models.ImageField(upload_to='destinos/galeria/', validators=[soar.videos.validar_foto], verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='imagemhospedagem',
            name='imagem',
            field=models.ImageField(upload_to='hospedagens/galeria/', validators=[soar.videos.validar_foto], verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='paginasobre',
            name='capa',
            field=models.ImageField(blank=True, help_text='Foto deitada e grande (1920 x 1080 px). Sem foto, usa uma ilustração da Soar.', null=True, upload_to='sobre/', validators=[soar.videos.validar_foto], verbose_name='Foto da capa'),
        ),
        migrations.AlterField(
            model_name='paginasobre',
            name='historia_foto',
            field=models.ImageField(blank=True, null=True, upload_to='sobre/', validators=[soar.videos.validar_foto], verbose_name='Foto ao lado do texto'),
        ),
        migrations.AlterField(
            model_name='slideinicio',
            name='imagem',
            field=models.ImageField(help_text='Foto deitada e grande (pelo menos 1600 px de largura). Ela ocupa a tela inteira, então o assunto principal deve ficar mais para a direita: o título aparece à esquerda.', upload_to='inicio/', validators=[soar.videos.validar_foto], verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='videodestino',
            name='capa',
            field=models.ImageField(blank=True, help_text='Opcional. Aparece antes de o vídeo tocar.', null=True, upload_to='destinos/videos/capas/', validators=[soar.videos.validar_foto], verbose_name='Foto de capa'),
        ),
        migrations.AlterField(
            model_name='videosoar60',
            name='capa',
            field=models.ImageField(blank=True, help_text='Opcional. Aparece antes de o vídeo tocar.', null=True, upload_to='soar60/capas/', validators=[soar.videos.validar_foto], verbose_name='Foto de capa'),
        ),
    ]
