# Generated by Django 5.2.17 on 2026-10-03 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0023_fotos_validadas'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenInstagram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField()),
                ('origem', models.CharField(max_length=64)),
                ('renovado_em', models.DateTimeField()),
                ('expira_em', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Token do Instagram',
                'verbose_name_plural': 'Token do Instagram',
            },
        ),
    ]
