# Generated by Django 5.2.17 on 2026-10-05 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0024_token_instagram'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextoBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Muito além do destino, uma Experiência', help_text='A frase grande, em letras brancas. Curta: até umas 8 palavras.', max_length=80, verbose_name='Título')),
                ('subtitulo', models.CharField(blank=True, default='Descubra viagens em grupo para destinos que você nunca vai esquecer.', help_text='Uma linha que completa o título. Em branco, não aparece.', max_length=160, verbose_name='Frase embaixo do título')),
            ],
            options={
                'verbose_name': 'Texto do banner',
                'verbose_name_plural': 'Texto do banner',
            },
        ),
    ]
