# Generated by Django 5.2.17 on 2026-10-05 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0025_texto_do_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destino',
            name='incluso',
            field=models.TextField(blank=True, help_text='Um item por linha. Linha que termina com ":" vira título, e as linhas de baixo ficam como tópicos dele (ex.: Passeios:). Não precisa pôr - ou • no começo.', verbose_name='O que está incluso'),
        ),
        migrations.AlterField(
            model_name='destino',
            name='informacoes',
            field=models.TextField(blank=True, help_text='Um item por linha. Linha que termina com ":" vira título, e as linhas de baixo ficam como tópicos dele (ex.: Passeios:). Não precisa pôr - ou • no começo.', verbose_name='Informações importantes'),
        ),
        migrations.AlterField(
            model_name='destino',
            name='nao_incluso',
            field=models.TextField(blank=True, help_text='Um item por linha. Linha que termina com ":" vira título, e as linhas de baixo ficam como tópicos dele (ex.: Passeios:). Não precisa pôr - ou • no começo. Em branco, a página só mostra o que está incluso.', verbose_name='O que não está incluso'),
        ),
    ]
