# Generated by Django 5.2.17 on 2026-10-06 18:23

import soar.videos
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0026_ajuda_titulos_nos_topicos'),
    ]

    operations = [
        migrations.CreateModel(
            name='FotoSoar60',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(blank=True, help_text='Foto deitada e grande (1920 x 1080 px). O texto fica do lado esquerdo, então o assunto da foto fica melhor à direita. Sem foto, usa a ilustração das montanhas.', null=True, upload_to='soar60/', validators=[soar.videos.validar_foto], verbose_name='Foto')),
            ],
            options={
                'verbose_name': 'Foto do Soar 60+',
                'verbose_name_plural': 'Foto do Soar 60+',
            },
        ),
    ]
