# Generated by Django 5.2.17 on 2026-10-06 18:32

import django.db.models.deletion
import soar.videos
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0028_pagina_soar_60'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paginasoar60',
            options={'verbose_name': 'Página Soar 60+', 'verbose_name_plural': 'Página Soar 60+'},
        ),
        migrations.AddField(
            model_name='paginasoar60',
            name='diferenciais_intro',
            field=models.CharField(blank=True, default='É o mesmo destino, organizado de outro jeito. O que a gente faz diferente nessas saídas:', max_length=300, verbose_name='Frase embaixo do título'),
        ),
        migrations.AddField(
            model_name='paginasoar60',
            name='diferenciais_titulo',
            field=models.CharField(default='O que muda numa viagem 60+', max_length=80, verbose_name='Título'),
        ),
        migrations.AddField(
            model_name='paginasoar60',
            name='passos_titulo',
            field=models.CharField(default='Como funciona', max_length=80, verbose_name='Título'),
        ),
        migrations.AddField(
            model_name='paginasoar60',
            name='perguntas_titulo',
            field=models.CharField(default='Perguntas de quem viaja com a gente', max_length=80, verbose_name='Título'),
        ),
        migrations.AddField(
            model_name='paginasoar60',
            name='subtitulo',
            field=models.TextField(blank=True, default='Viagens em grupo com ritmo tranquilo, guia do começo ao fim e hospedagem bem localizada, para quem quer conhecer novos lugares com conforto, segurança e companhia.', max_length=300, verbose_name='Frase da capa'),
        ),
        migrations.AddField(
            model_name='paginasoar60',
            name='texto_home',
            field=models.CharField(blank=True, default='Viagens pensadas para quem quer conhecer novos lugares com conforto, segurança e companhia.', help_text='O cartão "Soar 60+" da página inicial usa o título e a foto da capa e esta frase.', max_length=200, verbose_name='Frase do cartão na página inicial'),
        ),
        migrations.AddField(
            model_name='paginasoar60',
            name='titulo',
            field=models.CharField(default='Viajar não tem idade.', help_text='Vale também para o cartão do Soar 60+ na página inicial.', max_length=80, verbose_name='Título da capa'),
        ),
        migrations.AddField(
            model_name='paginasoar60',
            name='viagens_titulo',
            field=models.CharField(default='Viagens 60+', max_length=80, verbose_name='Título das viagens'),
        ),
        migrations.AddField(
            model_name='paginasoar60',
            name='videos_titulo',
            field=models.CharField(default='Veja como é viajar com a gente', max_length=80, verbose_name='Título dos vídeos'),
        ),
        migrations.AlterField(
            model_name='paginasoar60',
            name='foto',
            field=models.ImageField(blank=True, help_text='Foto deitada e grande (1920 x 1080 px). O texto fica do lado esquerdo, então o assunto da foto fica melhor à direita. Sem foto, usa a ilustração das montanhas.', null=True, upload_to='soar60/', validators=[soar.videos.validar_foto], verbose_name='Foto da capa'),
        ),
        migrations.CreateModel(
            name='ItemSoar60',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icone', models.CharField(choices=[('ic-onibus', 'Ônibus'), ('ic-aviao', 'Avião'), ('ic-barco', 'Barco'), ('ic-cama', 'Cama'), ('ic-hotel', 'Hotel'), ('ic-guia', 'Guia'), ('ic-grupo', 'Grupo'), ('ic-escudo', 'Seguro'), ('ic-camera', 'Câmera'), ('ic-coracao', 'Coração'), ('ic-talheres', 'Refeições'), ('ic-cafe', 'Café'), ('ic-ticket', 'Ingresso'), ('ic-mapa', 'Mapa'), ('ic-pin', 'Local'), ('ic-mala', 'Mala'), ('ic-mochila', 'Mochila'), ('ic-sol', 'Sol'), ('ic-lua', 'Noite'), ('ic-piscina', 'Piscina'), ('ic-wifi', 'Wi-Fi'), ('ic-ar', 'Ar-condicionado'), ('ic-relogio', 'Horário'), ('ic-calendario', 'Calendário'), ('ic-fone', 'Atendimento'), ('ic-estrela-c', 'Estrela'), ('ic-check', 'Confirmado')], default='ic-check', max_length=30, verbose_name='Ícone')),
                ('titulo', models.CharField(max_length=60, verbose_name='Título')),
                ('texto', models.TextField(blank=True, max_length=300, verbose_name='Texto')),
                ('ordem', models.PositiveSmallIntegerField(default=0, verbose_name='Ordem')),
                ('pagina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='destinations.paginasoar60')),
            ],
            options={
                'verbose_name': 'Cartão',
                'verbose_name_plural': 'Cartões de "O que muda"',
                'ordering': ['ordem', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PassoSoar60',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=80, verbose_name='Título')),
                ('texto', models.TextField(blank=True, max_length=400, verbose_name='Texto')),
                ('ordem', models.PositiveSmallIntegerField(default=0, verbose_name='Ordem')),
                ('pagina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passos', to='destinations.paginasoar60')),
            ],
            options={
                'verbose_name': 'Passo',
                'verbose_name_plural': 'Passos de "Como funciona"',
                'ordering': ['ordem', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PerguntaSoar60',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pergunta', models.CharField(max_length=160, verbose_name='Pergunta')),
                ('resposta', models.TextField(max_length=800, verbose_name='Resposta')),
                ('ordem', models.PositiveSmallIntegerField(default=0, verbose_name='Ordem')),
                ('pagina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perguntas', to='destinations.paginasoar60')),
            ],
            options={
                'verbose_name': 'Pergunta',
                'verbose_name_plural': 'Perguntas',
                'ordering': ['ordem', 'id'],
            },
        ),
    ]
