# Generated by Django 5.2.17 on 2026-10-06 19:14

"""O título do banner ganha "!" no fim, a pedido do dono.

Só troca o texto salvo se ele ainda for o original: se o dono já escreveu outro
título no painel, fica o dele.
"""
from django.db import migrations, models

ANTES = 'Muito além do destino, uma Experiência'
DEPOIS = ANTES + '!'


def trocar(apps, schema_editor):
    apps.get_model('destinations', 'TextoBanner').objects.filter(titulo=ANTES).update(titulo=DEPOIS)


def destrocar(apps, schema_editor):
    apps.get_model('destinations', 'TextoBanner').objects.filter(titulo=DEPOIS).update(titulo=ANTES)


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0030_texto_inicial_soar_60'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textobanner',
            name='titulo',
            field=models.CharField(default='Muito além do destino, uma Experiência!', help_text='A frase grande, em letras brancas. Curta: até umas 8 palavras.', max_length=80, verbose_name='Título'),
        ),
        migrations.RunPython(trocar, destrocar),
    ]
