# Generated by Django 5.2.17 on 2026-10-06 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0031_experiencia_com_exclamacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='interessado',
            name='pessoas',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Adultos'),
        ),
        migrations.AddField(
            model_name='interessado',
            name='quartos',
            field=models.JSONField(blank=True, default=list, verbose_name='Quartos'),
        ),
        migrations.AddField(
            model_name='interessado',
            name='saida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interessados', to='destinations.saida', verbose_name='Data de saída'),
        ),
        migrations.AddField(
            model_name='interessado',
            name='saida_texto',
            field=models.CharField(blank=True, max_length=120, verbose_name='Data escolhida'),
        ),
    ]
