# Generated by Django 5.2.17 on 2026-10-08 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0032_interessado_com_quartos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='precoquarto',
            name='tipo',
            field=models.CharField(choices=[('single', 'Single'), ('casal', 'Casal'), ('duplo', 'Duplo (Twin)'), ('triplo', 'Triplo'), ('bate_volta', 'Bate-volta (1 dia)')], max_length=12, verbose_name='Quarto'),
        ),
    ]
