# Generated by Django 5.2.17 on 2026-09-25 01:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contas', '0003_perfilagente_codigo'),
        ('destinations', '0010_saidas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente_nome', models.CharField(max_length=120, verbose_name='Nome do cliente')),
                ('cliente_telefone', models.CharField(blank=True, max_length=20, verbose_name='Telefone/WhatsApp')),
                ('cliente_email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail do cliente')),
                ('saida_texto', models.CharField(blank=True, editable=False, max_length=120, verbose_name='Saída')),
                ('acomodacao', models.CharField(choices=[('single', 'Single: 1 pessoa'), ('casal', 'Casal: 2 pessoas'), ('duplo', 'Duplo (Twin): 2 pessoas'), ('triplo', 'Triplo: 3 pessoas'), ('crianca', 'Criança (8 anos)')], default='casal', max_length=20, verbose_name='Acomodação')),
                ('pessoas', models.PositiveSmallIntegerField(default=2, verbose_name='Quantidade de pessoas')),
                ('valor', models.DecimalField(blank=True, decimal_places=2, help_text='O valor que a agência passou ao cliente.', max_digits=10, null=True, verbose_name='Valor total (R$)')),
                ('validade', models.DateField(blank=True, null=True, verbose_name='Válido até')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('status', models.CharField(choices=[('enviado', 'Enviado ao cliente'), ('aceito', 'Aceito'), ('recusado', 'Recusado')], default='enviado', max_length=10, verbose_name='Situação')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('agencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orcamentos', to='contas.perfilagente', verbose_name='Agência')),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orcamentos', to='destinations.destino', verbose_name='Destino')),
                ('saida', models.ForeignKey(blank=True, help_text='Em branco, a data fica a combinar.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orcamentos', to='destinations.saida', verbose_name='Data de saída')),
            ],
            options={
                'verbose_name': 'Orçamento',
                'verbose_name_plural': 'Orçamentos',
                'ordering': ['-criado_em'],
            },
        ),
    ]
