# Generated by Django 5.2.17 on 2026-10-03 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencia', '0002_crianca_nao_paga'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento',
            name='idades_criancas',
            field=models.CharField(blank=True, help_text='Separadas por vírgula, ex.: 4, 7. Em branco se não vai criança.', max_length=60, verbose_name='Idades das crianças (CHD)'),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='acomodacao',
            field=models.CharField(choices=[('single', 'Single: 1 pessoa'), ('casal', 'Casal: 2 pessoas'), ('duplo', 'Duplo (Twin): 2 pessoas'), ('triplo', 'Triplo: 3 pessoas')], default='casal', max_length=20, verbose_name='Acomodação'),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='pessoas',
            field=models.PositiveSmallIntegerField(default=2, verbose_name='Adultos'),
        ),
    ]
