# Generated by Django 5.2.17 on 2026-10-03 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencia', '0003_criancas_adicional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orcamento',
            name='idades_criancas',
            field=models.CharField(blank=True, help_text='De 0 a 8 anos, separadas por vírgula, ex.: 4, 7. Em branco se não vai criança.', max_length=60, verbose_name='Idades das crianças (CHD)'),
        ),
    ]
