# Generated by Django 5.2.17 on 2026-10-03 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencia', '0005_validade_72_horas'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento',
            name='enviado_em',
            field=models.DateTimeField(blank=True, help_text='Em branco: o e-mail não saiu.', null=True, verbose_name='PDF enviado por e-mail em'),
        ),
    ]
