# Generated by Django 5.2.17 on 2026-10-06 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencia', '0006_orcamento_enviado_por_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento',
            name='quartos',
            field=models.JSONField(blank=True, default=list, verbose_name='Quartos'),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='acomodacao',
            field=models.CharField(choices=[('single', 'Single: 1 pessoa'), ('casal', 'Casal: 2 pessoas'), ('duplo', 'Duplo (Twin): 2 pessoas'), ('triplo', 'Triplo: 3 pessoas')], default='casal', help_text='O primeiro tipo de quarto escolhido (os outros estão em "quartos").', max_length=20, verbose_name='Acomodação'),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='pessoas',
            field=models.PositiveSmallIntegerField(default=2, help_text='Soma das pessoas de todos os quartos.', verbose_name='Adultos'),
        ),
    ]
