# Generated by Django 5.2.17 on 2026-10-08 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencia', '0007_varios_quartos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orcamento',
            name='acomodacao',
            field=models.CharField(choices=[('single', 'Single: 1 pessoa'), ('casal', 'Casal: 2 pessoas'), ('duplo', 'Duplo (Twin): 2 pessoas'), ('triplo', 'Triplo: 3 pessoas'), ('bate_volta', 'Bate-volta (1 dia, sem hospedagem)')], default='casal', help_text='O primeiro tipo de quarto escolhido (os outros estão em "quartos").', max_length=20, verbose_name='Acomodação'),
        ),
    ]
