# Generated by Django 5.2.17 on 2026-09-18 02:46

import contas.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contas', '0001_email_unico'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilAgente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(max_length=160, verbose_name='Razão social')),
                ('cnpj', models.CharField(help_text='14 números, sem pontos nem barra.', max_length=14, unique=True, validators=[contas.models.validar_cnpj], verbose_name='CNPJ')),
                ('cadastur', models.CharField(max_length=30, verbose_name='CADASTUR')),
                ('whatsapp', models.CharField(max_length=20, verbose_name='WhatsApp')),
                ('aprovado', models.BooleanField(default=False, help_text='Marque depois de conferir o CNPJ e o CADASTUR da agência.', verbose_name='Aprovado pela Soar')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Cadastrado em')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agente', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Agente B2B',
                'verbose_name_plural': 'Agentes B2B',
                'ordering': ['razao_social'],
            },
        ),
    ]
