# Generated by Django 5.2.17 on 2026-09-23 01:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('destinations', '0009_tira_travessao_do_conteudo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60, unique=True, verbose_name='Nome')),
                ('slug', models.SlugField(help_text='Preenchido sozinho a partir do nome.', max_length=70, unique=True, verbose_name='Endereço')),
                ('icone', models.CharField(choices=[('info', 'Informação (i)'), ('pin', 'Alfinete de mapa'), ('mapa', 'Mapa'), ('calendario', 'Calendário'), ('relogio', 'Relógio'), ('camera', 'Câmera'), ('onibus', 'Ônibus'), ('cama', 'Cama'), ('hotel', 'Hotel'), ('mala', 'Mala'), ('mochila', 'Mochila'), ('doc', 'Documento'), ('escudo', 'Escudo (segurança)'), ('guia', 'Guia'), ('grupo', 'Grupo de pessoas'), ('coracao', 'Coração'), ('estrela', 'Estrela'), ('ticket', 'Ingresso')], default='pin', help_text='Aparece na aba da categoria, no topo do blog.', max_length=20, verbose_name='Ícone')),
                ('ordem', models.PositiveSmallIntegerField(default=0, help_text='Menor aparece primeiro.', verbose_name='Ordem')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Artigo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=160, verbose_name='Título')),
                ('slug', models.SlugField(help_text='Parte final do link do artigo. Preenchido sozinho a partir do título; só mude se souber o que está fazendo, porque links antigos param de funcionar.', max_length=170, unique=True, verbose_name='Endereço')),
                ('resumo', models.CharField(help_text='Uma ou duas frases. Aparece no cartão do blog e embaixo do título do artigo.', max_length=240, verbose_name='Resumo')),
                ('capa', models.ImageField(blank=True, help_text='Foto larga (deitada). Sem foto, a página usa o fundo verde da Soar.', null=True, upload_to='blog/capas/', verbose_name='Foto de capa')),
                ('autor', models.CharField(default='Equipe Soar', max_length=80, verbose_name='Autor')),
                ('publicado', models.BooleanField(default=False, help_text='Desmarcado = rascunho: só você vê. Marcado = vai ao ar na data de publicação.', verbose_name='Publicado')),
                ('data_publicacao', models.DateField(default=django.utils.timezone.localdate, help_text='Escolha no calendário. Com data futura, o artigo fica agendado e entra no ar sozinho nesse dia.', verbose_name='Data de publicação')),
                ('destaque', models.BooleanField(default=False, help_text='O artigo em destaque mais recente abre o blog em tamanho grande.', verbose_name='Destaque')),
                ('etiqueta', models.CharField(blank=True, help_text='Palavra curta sobre a foto do cartão, ex.: "Jalapão". Em branco, usa o nome da categoria.', max_length=40, verbose_name='Etiqueta do cartão')),
                ('cor_etiqueta', models.CharField(choices=[('verde', 'Verde'), ('teal', 'Verde-água'), ('azul', 'Azul'), ('roxo', 'Roxo'), ('laranja', 'Laranja'), ('rosa', 'Rosa')], default='verde', max_length=10, verbose_name='Cor da etiqueta')),
                ('introducao', models.TextField(blank=True, help_text='Vem antes das seções. Para começar um parágrafo novo, deixe uma linha em branco.', verbose_name='Texto de abertura')),
                ('leituras', models.PositiveIntegerField(default=0, editable=False, verbose_name='Leituras')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('destino', models.ForeignKey(blank=True, help_text='Opcional. O final do artigo ganha um botão para a página dessa viagem.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artigos', to='destinations.destino', verbose_name='Viagem ligada ao artigo')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='artigos', to='blog.categoria', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Artigo',
                'verbose_name_plural': 'Artigos',
                'ordering': ['-data_publicacao', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Atracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveSmallIntegerField(default=0, verbose_name='Ordem')),
                ('nome', models.CharField(max_length=80, verbose_name='Nome')),
                ('descricao', models.CharField(blank=True, max_length=140, verbose_name='Frase curta')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='blog/atracoes/', verbose_name='Foto')),
                ('artigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atracoes', to='blog.artigo')),
            ],
            options={
                'verbose_name': 'Atração',
                'verbose_name_plural': 'Atrações (grade de fotos)',
                'ordering': ['ordem', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Secao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveSmallIntegerField(default=0, verbose_name='Ordem')),
                ('titulo', models.CharField(help_text='Vira também um atalho no quadro "Neste artigo você vai ver".', max_length=120, verbose_name='Título da seção')),
                ('icone', models.CharField(choices=[('info', 'Informação (i)'), ('pin', 'Alfinete de mapa'), ('mapa', 'Mapa'), ('calendario', 'Calendário'), ('relogio', 'Relógio'), ('camera', 'Câmera'), ('onibus', 'Ônibus'), ('cama', 'Cama'), ('hotel', 'Hotel'), ('mala', 'Mala'), ('mochila', 'Mochila'), ('doc', 'Documento'), ('escudo', 'Escudo (segurança)'), ('guia', 'Guia'), ('grupo', 'Grupo de pessoas'), ('coracao', 'Coração'), ('estrela', 'Estrela'), ('ticket', 'Ingresso')], default='info', max_length=20, verbose_name='Ícone do atalho')),
                ('texto', models.TextField(blank=True, help_text='Para começar um parágrafo novo, deixe uma linha em branco.', verbose_name='Texto')),
                ('foto', models.ImageField(blank=True, help_text='Opcional. Aparece depois do texto.', null=True, upload_to='blog/secoes/', verbose_name='Foto')),
                ('nota', models.TextField(blank=True, help_text='Opcional. Um recado em caixa verde, ex.: uma dica importante.', verbose_name='Caixa de destaque')),
                ('dicas', models.TextField(blank=True, help_text='Opcional. Um item por linha.', verbose_name='Lista com ✓')),
                ('melhores_meses', models.CharField(blank=True, max_length=40, verbose_name='Meses de ótima época')),
                ('meses_bons', models.CharField(blank=True, max_length=40, verbose_name='Meses de boa época')),
                ('mostrar_atracoes', models.BooleanField(default=False, help_text='Coloca nesta seção a grade de atrações cadastrada no fim do artigo.', verbose_name='Mostrar as atrações aqui')),
                ('artigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secoes', to='blog.artigo')),
            ],
            options={
                'verbose_name': 'Seção',
                'verbose_name_plural': 'Seções do artigo',
                'ordering': ['ordem', 'id'],
            },
        ),
    ]
