# Generated by Django 5.2.17 on 2026-09-23 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_publica_os_cartoes_da_vitrine'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artigo',
            options={'ordering': ['-data_publicacao', 'id'], 'verbose_name': 'Artigo', 'verbose_name_plural': 'Artigos'},
        ),
    ]
