# Generated by Django 5.2.17 on 2026-09-25 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_ordem_da_vitrine'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
                ('origem', models.CharField(blank=True, max_length=120, verbose_name='Onde se inscreveu')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Inscrito em')),
            ],
            options={
                'verbose_name': 'Inscrição na newsletter',
                'verbose_name_plural': 'Newsletter (inscritos)',
                'ordering': ['-criado_em'],
            },
        ),
    ]
