# Generated by Django 5.2.17 on 2026-09-28 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_newsletter"),
    ]

    operations = [
        migrations.AddField(
            model_name="inscricao",
            name="confirmada_em",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Confirmada em"
            ),
        ),
    ]
