# Generated by Django 5.2.17 on 2026-10-03 03:04

import soar.videos
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_newsletter_confirmada'),
    ]

    operations = [
        migrations.AddField(
            model_name='secao',
            name='video',
            field=models.FileField(blank=True, help_text='Opcional. Aparece depois da foto. MP4 ou WebM, até 100 MB. Vídeos curtos (até 1 minuto) carregam mais rápido, principalmente no celular.', upload_to='blog/videos/', validators=[soar.videos.validar_video], verbose_name='Vídeo'),
        ),
    ]
