# Generated by Django 5.2.17 on 2026-10-03 05:13

import soar.videos
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_videos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artigo',
            name='capa',
            field=models.ImageField(blank=True, help_text='Foto larga (deitada). Sem foto, a página usa o fundo verde da Soar.', null=True, upload_to='blog/capas/', validators=[soar.videos.validar_foto], verbose_name='Foto de capa'),
        ),
        migrations.AlterField(
            model_name='atracao',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='blog/atracoes/', validators=[soar.videos.validar_foto], verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='secao',
            name='foto',
            field=models.ImageField(blank=True, help_text='Opcional. Aparece depois do texto.', null=True, upload_to='blog/secoes/', validators=[soar.videos.validar_foto], verbose_name='Foto'),
        ),
    ]
