# Generated by Django 5.2.17 on 2026-10-04 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_fotos_validadas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artigo',
            name='cor_etiqueta',
        ),
    ]
