# Generated by Django 5.2.17 on 2026-10-06 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_varias_viagens_por_artigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='icone',
            field=models.CharField(choices=[('info', 'Informação (i)'), ('pin', 'Alfinete de mapa'), ('mapa', 'Mapa'), ('calendario', 'Calendário'), ('relogio', 'Relógio'), ('camera', 'Câmera'), ('onibus', 'Ônibus'), ('4x4', 'Carro 4x4'), ('cama', 'Cama'), ('hotel', 'Hotel'), ('mala', 'Mala'), ('mochila', 'Mochila'), ('doc', 'Documento'), ('escudo', 'Escudo (segurança)'), ('guia', 'Guia'), ('grupo', 'Grupo de pessoas'), ('coracao', 'Coração'), ('estrela', 'Estrela'), ('ticket', 'Ingresso')], default='pin', help_text='Aparece na aba da categoria, no topo do blog.', max_length=20, verbose_name='Ícone'),
        ),
        migrations.AlterField(
            model_name='secao',
            name='icone',
            field=models.CharField(choices=[('info', 'Informação (i)'), ('pin', 'Alfinete de mapa'), ('mapa', 'Mapa'), ('calendario', 'Calendário'), ('relogio', 'Relógio'), ('camera', 'Câmera'), ('onibus', 'Ônibus'), ('4x4', 'Carro 4x4'), ('cama', 'Cama'), ('hotel', 'Hotel'), ('mala', 'Mala'), ('mochila', 'Mochila'), ('doc', 'Documento'), ('escudo', 'Escudo (segurança)'), ('guia', 'Guia'), ('grupo', 'Grupo de pessoas'), ('coracao', 'Coração'), ('estrela', 'Estrela'), ('ticket', 'Ingresso')], default='info', max_length=20, verbose_name='Ícone do atalho'),
        ),
    ]
