# Generated by Django 5.2.17 on 2026-10-06 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_icone_4x4'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artigo',
            name='titulo',
            field=models.CharField(help_text='Para um subtítulo, dê Enter: a segunda linha aparece embaixo do título, em letra menor.', max_length=160, verbose_name='Título'),
        ),
    ]
