# Generated by Django 5.2.17 on 2026-10-10 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_titulo_com_subtitulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atracao',
            name='descricao',
            field=models.TextField(blank=True, help_text='O cartão mostra o começo; o texto inteiro abre ao clicar em "Ler mais".', max_length=1500, verbose_name='Breve relato'),
        ),
    ]
