# Generated by Django 5.2.17 on 2026-09-03 00:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0003_destino_destino_nome_idx_destino_destino_pais_idx_and_more'),
        ('reviews', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacao',
            name='autor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avaliacoes', to=settings.AUTH_USER_MODEL, verbose_name='Cliente'),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='ip',
            field=models.GenericIPAddressField(blank=True, help_text='Registrado no envio, para apuração de abuso.', null=True, verbose_name='IP de origem'),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='publicada',
            field=models.BooleanField(default=False, help_text='Enquanto estiver desmarcada, a avaliação não aparece no site.', verbose_name='Publicada'),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='nome_autor',
            field=models.CharField(help_text='Preenchido a partir da conta de quem avaliou.', max_length=80, verbose_name='Nome exibido'),
        ),
        migrations.AddConstraint(
            model_name='avaliacao',
            constraint=models.UniqueConstraint(condition=models.Q(('autor__isnull', False)), fields=('destino', 'autor'), name='uma_avaliacao_por_pessoa_por_destino'),
        ),
    ]
