# Generated by Django 5.2.17 on 2026-09-22 23:42

import reviews.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_publicar_avaliacoes_antigas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacao',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=reviews.models.caminho_foto_avaliacao, verbose_name='Foto da viagem (opcional)'),
        ),
    ]
