# Generated by Django 5.2.17 on 2026-09-30 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_alter_avaliacao_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacao',
            name='nome_autor',
            field=models.CharField(help_text='O nome de quem viajou, como vai aparecer no site.', max_length=80, verbose_name='Nome exibido'),
        ),
    ]
