# Generated by Django 5.2.17 on 2026-10-03 05:13

import reviews.models
import soar.videos
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_nome_digitado_no_painel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacao',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=reviews.models.caminho_foto_avaliacao, validators=[soar.videos.validar_foto], verbose_name='Foto da viagem (opcional)'),
        ),
    ]
