# Generated by Django 5.2.17 on 2026-09-02 23:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('destinations', '0002_destino_dias_destino_estado_destino_hospedagem_sub_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acomodacao', models.CharField(choices=[('single', 'Single — 1 pessoa'), ('duplo', 'Duplo/Casal — 2 pessoas'), ('triplo', 'Triplo — 3 pessoas'), ('crianca', 'Criança (até 10 anos)')], default='duplo', max_length=20, verbose_name='Acomodação')),
                ('pessoas', models.PositiveSmallIntegerField(default=1, verbose_name='Quantidade de pessoas')),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='Telefone/WhatsApp')),
                ('observacao', models.TextField(blank=True, verbose_name='Observações')),
                ('preco_estimado', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Preço estimado por pessoa (R$)')),
                ('saida', models.CharField(blank=True, help_text='Período que estava anunciado quando o cliente reservou.', max_length=120, verbose_name='Saída pedida')),
                ('status', models.CharField(choices=[('pendente', 'Aguardando contato'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada')], default='pendente', max_length=12, verbose_name='Situação')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Pedido em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='destinations.destino', verbose_name='Destino')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to=settings.AUTH_USER_MODEL, verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'ordering': ['-criado_em'],
            },
        ),
    ]
