# Generated by Django 5.2.17 on 2026-09-23 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0005_alter_reserva_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='acomodacao',
            field=models.CharField(choices=[('single', 'Single: 1 pessoa'), ('casal', 'Casal: 2 pessoas'), ('duplo', 'Duplo (Twin): 2 pessoas'), ('triplo', 'Triplo: 3 pessoas'), ('crianca', 'Criança (8 anos)')], default='casal', max_length=20, verbose_name='Acomodação'),
        ),
    ]
