# Generated by Django 5.2.17 on 2026-09-25 01:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0003_perfilagente_codigo'),
        ('reservas', '0006_alter_reserva_acomodacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='agencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas', to='contas.perfilagente', verbose_name='Agência parceira'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='nota_agencia',
            field=models.TextField(blank=True, help_text='Escritas pela agência ou pela Soar. O cliente não vê.', verbose_name='Anotações do atendimento'),
        ),
    ]
