# Generated by Django 5.2.17 on 2026-09-25 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0007_reserva_agencia_reserva_nota_agencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='acomodacao',
            field=models.CharField(choices=[('single', 'Single: 1 pessoa'), ('casal', 'Casal: 2 pessoas'), ('duplo', 'Duplo (Twin): 2 pessoas'), ('triplo', 'Triplo: 3 pessoas'), ('crianca', 'Criança até 8 anos (não paga)')], default='casal', max_length=20, verbose_name='Acomodação'),
        ),
    ]
