# Generated by Django 5.2.17 on 2026-09-25 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0008_crianca_nao_paga'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='preco_estimado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Preço estimado por pessoa (R$)'),
        ),
    ]
