# Generated by Django 5.2.17 on 2026-10-03 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0009_preco_por_pessoa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='acomodacao',
            field=models.CharField(choices=[('single', 'Single: 1 pessoa'), ('casal', 'Casal: 2 pessoas'), ('duplo', 'Duplo (Twin): 2 pessoas'), ('triplo', 'Triplo: 3 pessoas')], default='casal', max_length=20, verbose_name='Acomodação'),
        ),
    ]
